CREATE TABLE forge_repositories
(
    project_id        uuid PRIMARY KEY,
    connection_id     uuid        NOT NULL,
    external_id       text        NOT NULL,
    full_path         text        NOT NULL,
    web_url           text        NOT NULL,
    description       text        NOT NULL DEFAULT '',
    topics            text[]      NOT NULL DEFAULT '{}',
    readme_md         text,
    readme_truncated  boolean     NOT NULL DEFAULT false,
    languages         jsonb       NOT NULL DEFAULT '{}'::jsonb,
    default_branch    text,
    archived          boolean     NOT NULL DEFAULT false,
    visibility        text        NOT NULL,
    stars             integer     NOT NULL DEFAULT 0,
    license           text,
    pushed_at         timestamptz,
    source_updated_at timestamptz,
    synced_at         timestamptz NOT NULL DEFAULT now(),
    orphaned_at       timestamptz,
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT forge_repositories_project_id_fkey FOREIGN KEY (project_id) REFERENCES nodes (id) ON DELETE CASCADE,
    CONSTRAINT forge_repositories_connection_id_fkey FOREIGN KEY (connection_id) REFERENCES forge_connections (id) ON DELETE CASCADE,
    CONSTRAINT forge_repositories_external_key UNIQUE (connection_id, external_id),
    CONSTRAINT forge_repositories_visibility_check CHECK (visibility IN ('public', 'internal', 'private')),
    CONSTRAINT forge_repositories_languages_object_check CHECK (jsonb_typeof(languages) = 'object')
);
